backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
public_folder: "/images"
site_url: "https://praveenjuge.com/"
display_url: "https://praveenjuge.com/"
collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "og", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Home"
    name: "home"
    folder: "content"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
